name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies and run tests
        run: mvn clean verify -X

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Verify coverage threshold
        run: |
          THRESHOLD=40
          COVERAGE=$(grep -Po '<line-rate>\K[0-9.]+' target/site/jacoco/jacoco.xml | awk '{print $1 * 100}')
          if [ -z "$COVERAGE" ]; then
            echo "Error: Unable to retrieve coverage. Check if the JaCoCo report was generated correctly."
            exit 1
          fi
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "Coverage below threshold: $COVERAGE%"
            exit 1
          fi
          echo "Coverage meets the threshold: $COVERAGE%"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
