name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies and run tests
        run: mvn clean verify -X

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Check if JaCoCo HTML report exists
        run: |
          if [ -f target/site/jacoco/index.html ]; then
            echo "JaCoCo HTML report found."
          else
            echo "JaCoCo HTML report not found at target/site/jacoco/index.html"
            exit 1
          fi

      - name: Debug JaCoCo HTML report
        run: |
          grep 'Total</td>' target/site/jacoco/index.html || echo "No Total coverage found in HTML report."

      - name: Verify coverage threshold
        run: |
          THRESHOLD=40
          
          # Extraer la línea con cobertura total
          LINE=$(grep '<td>Total</td><td class="bar">' target/site/jacoco/index.html)
          
          if [ -z "$LINE" ]; then
            echo "Error: Unable to find Total coverage line in JaCoCo HTML report."
            exit 1
          fi
          
          # Extraer el porcentaje de cobertura
          TOTAL_COVERAGE=$(echo "$LINE" | grep -Po '(?<=<td class="ctr2">)[0-9]+(?=%)')
          
          if [ -z "$TOTAL_COVERAGE" ]; then
            echo "Error: Unable to extract Total coverage percentage."
            exit 1
          fi
          
          echo "Extracted Coverage: $TOTAL_COVERAGE%"
          
          # Comparar con el umbral
          if (( TOTAL_COVERAGE < THRESHOLD )); then
            echo "Coverage below threshold: $TOTAL_COVERAGE%"
            exit 1
          fi
          
          echo "Coverage meets the threshold: $TOTAL_COVERAGE%"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
