name: CI Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies and run tests
        run: mvn clean verify -X

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Debug JaCoCo report
        run: |
          if [ -f target/site/jacoco/jacoco.xml ]; then
            echo "JaCoCo report exists:"
            cat target/site/jacoco/jacoco.xml
          else
            echo "JaCoCo report not found at target/site/jacoco/jacoco.xml"
            exit 1
          fi

      - name: Verify coverage threshold
        run: |
          THRESHOLD=40
          MISSED=$(grep -Po '<counter type="INSTRUCTION" missed="\K[0-9]+' target/site/jacoco/jacoco.xml | awk '{sum+=$1} END {print sum}')
          COVERED=$(grep -Po '<counter type="INSTRUCTION" covered="\K[0-9]+' target/site/jacoco/jacoco.xml | awk '{sum+=$1} END {print sum}')
          if [ -z "$MISSED" ] || [ -z "$COVERED" ]; then
            echo "Error: Unable to retrieve instruction data. Check the JaCoCo report."
            exit 1
          fi
          TOTAL=$((MISSED + COVERED))
          COVERAGE=$(echo "scale=2; ($COVERED / $TOTAL) * 100" | bc)
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "Coverage below threshold: $COVERAGE%"
            exit 1
          fi
          echo "Coverage meets the threshold: $COVERAGE%"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
